### ISSUE TITLE
Weback connection expires?

### ISSUE THREAD

**Issue by muskatCZ** [ltekieli/floureon-cloud#1]
Hi,

I have a question. I was able to integrate my Floureon thermostats into HA. But it seems that the connection expires after few hours and data from thermostats stop updating. Is there a way how to fix it, please?
For your reference, I have following configuration per each thermostat:
   - platform: floureon-cloud
     login: loginname
     password: *****
     device: deviceID
     name: MyCustomName

Thank you very much for your help, Roman

**Comment by ltekieli** [comment]
Hello, I don't use this extension any more. I gave up after fighting with authentication, instabilities of the device and the backend. I reflashed my device with https://github.com/ltekieli/MikesThermostat and now everything works perfect over local mqtt connection.
